update_interval: 5
commission_stock: 0.0004
commission_future: 0.00025
port: 8080
pairs:
  - id: "head"
    stock_ticker: "HEAD"
    future_ticker: "HDZ6"
    future_uid: "53ecf2f0-7442-416c-a00d-db1e72a44dcb"